#!/usr/bin/env bash
set -euo pipefail

# Parse flags. --silent (alias -y) skips the interactive skill-name prompt and uses the
# pinned DEFAULT_SKILL_NAME directly, so the script works under non-interactive automation
# where `read` would fail on EOF. Mirrors the rest of the *-wisdom family.
SILENT=""
while [ $# -gt 0 ]; do
  case "$1" in
    --silent|-y) SILENT="true" ;;
    *)
      echo "Error: unknown argument: $1" >&2
      exit 1
      ;;
  esac
  shift
done

# ── setup-doc-skill.sh ─────────────────────────────────
# Wires the css-wisdom doc-lookup skill: creates symlinks
# for docs/ and docs-ja/ inside the skill directory, then
# symlinks the skill into the user-scope skills directory
# (~/.claude/skills/).
#
# SKILL.md is generated by `generate-css-wisdom.js` (run
# via `pnpm generate:css-wisdom`, which `pnpm setup:doc-skill`
# runs automatically before this script).
# This script does NOT overwrite SKILL.md.
# ────────────────────────────────────────────────────────

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"

# Skill name is pinned to "css-wisdom": generate-css-wisdom.js writes SKILL.md/descriptions.json
# under .claude/skills/css-wisdom/ and the .gitignore entries reference that exact path, so the
# name cannot vary here (unlike the other *-wisdom repos, which generate SKILL.md inline).
DEFAULT_SKILL_NAME="css-wisdom"

# Prompt for the skill name for parity with the rest of the *-wisdom family (skipped under --silent).
if [ -n "$SILENT" ]; then
  SKILL_NAME="$DEFAULT_SKILL_NAME"
else
  echo ""
  echo "=== css-wisdom Skill Setup ==="
  echo ""
  read -rp "Skill name [$DEFAULT_SKILL_NAME]: " SKILL_NAME
  SKILL_NAME="${SKILL_NAME:-$DEFAULT_SKILL_NAME}"
fi

# The name is pinned (see above); a custom name would point at a skill dir with no generated
# SKILL.md/descriptions.json. Reject it explicitly instead of failing later with a confusing error.
if [ "$SKILL_NAME" != "$DEFAULT_SKILL_NAME" ]; then
  echo "Error: this repo pins the skill name to '$DEFAULT_SKILL_NAME' (generate-css-wisdom.js and .gitignore reference it)." >&2
  echo "Custom names are not supported here; press Enter at the prompt (or use --silent) to accept the default." >&2
  exit 1
fi

# Resolve the main repo root (handles git worktrees correctly)
# Use the main worktree path so symlinks survive worktree removal
REPO_ROOT="$(git -C "$ROOT_DIR" worktree list | head -1 | awk '{print $1}')"

SKILL_DIR="$ROOT_DIR/.claude/skills/$SKILL_NAME"
DOCS_DIR="$ROOT_DIR/src/content/docs"
GLOBAL_SKILLS_DIR="$HOME/.claude/skills"

# Validate docs directory exists
if [ ! -d "$DOCS_DIR" ]; then
  echo "Error: Documentation directory not found at $DOCS_DIR"
  exit 1
fi

# Helper: replace a symlink or file at the given path
ensure_symlink() {
  local link_path="$1"
  local target="$2"
  if [ -L "$link_path" ] || [ -e "$link_path" ]; then
    rm -rf "$link_path"
  fi
  ln -s "$target" "$link_path"
}

# Create skill directory
mkdir -p "$SKILL_DIR"

# Create symlink to docs directory inside the skill
ensure_symlink "$SKILL_DIR/docs" "$REPO_ROOT/src/content/docs"
echo "  Created docs symlink -> $REPO_ROOT/src/content/docs"

# Create symlink to Japanese docs if they exist
if [ -d "$ROOT_DIR/src/content/docs-ja" ]; then
  ensure_symlink "$SKILL_DIR/docs-ja" "$REPO_ROOT/src/content/docs-ja"
  echo "  Created docs-ja symlink -> $REPO_ROOT/src/content/docs-ja"
fi

# Verify SKILL.md exists (generated by generate-css-wisdom.js before this script runs)
if [ ! -f "$SKILL_DIR/SKILL.md" ]; then
  echo "Error: $SKILL_DIR/SKILL.md not found."
  echo "generate-css-wisdom.js should have run first (pnpm setup:doc-skill chains it)."
  echo "Try: pnpm generate:css-wisdom && bash scripts/setup-doc-skill.sh"
  exit 1
fi
echo "  SKILL.md present (generated by generate-css-wisdom.js)"

# Symlink into global skills directory.
# Point at the main-worktree path so the global link survives worktree removal.
mkdir -p "$GLOBAL_SKILLS_DIR"
ensure_symlink "$GLOBAL_SKILLS_DIR/$SKILL_NAME" "$REPO_ROOT/.claude/skills/$SKILL_NAME"

echo ""
echo "Done! Skill '$SKILL_NAME' is ready."
echo ""
echo "  Project skill: $SKILL_DIR"
echo "  Global symlink: $GLOBAL_SKILLS_DIR/$SKILL_NAME"
echo ""
echo "You can now use it in Claude Code with: /$SKILL_NAME <topic>"
echo ""
