#!/usr/bin/env bash
set -euo pipefail

# ── setup-doc-skill.sh ─────────────────────────────────
# Wires the css-wisdom doc-lookup skill: creates symlinks
# for docs/ and docs-ja/ inside the skill directory, then
# symlinks the skill into the user-scope skills directory
# (~/.claude/skills/).
#
# SKILL.md is generated by `generate-css-wisdom.js` (run
# via `pnpm generate:css-wisdom`, which `pnpm setup:doc-skill`
# runs automatically before this script).
# This script does NOT overwrite SKILL.md.
# ────────────────────────────────────────────────────────

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"

# Skill name is hardcoded to match generate-css-wisdom.js output and .gitignore entries.
SKILL_NAME="css-wisdom"

# Resolve the main repo root (handles git worktrees correctly)
# Use the main worktree path so symlinks survive worktree removal
REPO_ROOT="$(git -C "$ROOT_DIR" worktree list | head -1 | awk '{print $1}')"

SKILL_DIR="$ROOT_DIR/.claude/skills/$SKILL_NAME"
DOCS_DIR="$ROOT_DIR/src/content/docs"
GLOBAL_SKILLS_DIR="$HOME/.claude/skills"

echo ""
echo "=== css-wisdom Skill Setup ==="
echo ""

# Validate docs directory exists
if [ ! -d "$DOCS_DIR" ]; then
  echo "Error: Documentation directory not found at $DOCS_DIR"
  exit 1
fi

# Helper: replace a symlink or file at the given path
ensure_symlink() {
  local link_path="$1"
  local target="$2"
  if [ -L "$link_path" ] || [ -e "$link_path" ]; then
    rm -rf "$link_path"
  fi
  ln -s "$target" "$link_path"
}

# Create skill directory
mkdir -p "$SKILL_DIR"

# Create symlink to docs directory inside the skill
ensure_symlink "$SKILL_DIR/docs" "$REPO_ROOT/src/content/docs"
echo "  Created docs symlink -> $REPO_ROOT/src/content/docs"

# Create symlink to Japanese docs if they exist
if [ -d "$ROOT_DIR/src/content/docs-ja" ]; then
  ensure_symlink "$SKILL_DIR/docs-ja" "$REPO_ROOT/src/content/docs-ja"
  echo "  Created docs-ja symlink -> $REPO_ROOT/src/content/docs-ja"
fi

# Verify SKILL.md exists (generated by generate-css-wisdom.js before this script runs)
if [ ! -f "$SKILL_DIR/SKILL.md" ]; then
  echo "Error: $SKILL_DIR/SKILL.md not found."
  echo "generate-css-wisdom.js should have run first (pnpm setup:doc-skill chains it)."
  echo "Try: pnpm generate:css-wisdom && bash scripts/setup-doc-skill.sh"
  exit 1
fi
echo "  SKILL.md present (generated by generate-css-wisdom.js)"

# Symlink into global skills directory.
# Point at the main-worktree path so the global link survives worktree removal.
mkdir -p "$GLOBAL_SKILLS_DIR"
ensure_symlink "$GLOBAL_SKILLS_DIR/$SKILL_NAME" "$REPO_ROOT/.claude/skills/$SKILL_NAME"

echo ""
echo "Done! Skill '$SKILL_NAME' is ready."
echo ""
echo "  Project skill: $SKILL_DIR"
echo "  Global symlink: $GLOBAL_SKILLS_DIR/$SKILL_NAME"
echo ""
echo "You can now use it in Claude Code with: /$SKILL_NAME <topic>"
echo ""
