#!/usr/bin/env bash
set -euo pipefail

# Wires the css-wisdom doc-lookup skill for Claude Code and/or Codex.
# SKILL.md is generated by scripts/generate-css-wisdom.js before this script
# runs via the package.json setup scripts.

TARGET_MODE="auto"

while [ $# -gt 0 ]; do
  case "$1" in
    --silent|-y) shift ;;
    --target)
      shift
      if [ $# -eq 0 ]; then
        echo "Error: --target requires one of: auto, claude, codex, both" >&2
        exit 1
      fi
      TARGET_MODE="$1"
      shift
      ;;
    --target=*)
      TARGET_MODE="${1#--target=}"
      shift
      ;;
    --) shift; break ;;
    -*) echo "Error: unknown flag '$1'" >&2; exit 1 ;;
    *) break ;;
  esac
done

case "$TARGET_MODE" in
  auto|claude|codex|both) ;;
  *)
    echo "Error: --target must be one of: auto, claude, codex, both" >&2
    exit 1
    ;;
esac

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"

# Pinned to match generate-css-wisdom.js, .gitignore, and existing skill usage.
DEFAULT_SKILL_NAME="css-wisdom"
SKILL_NAME="${1:-${SKILL_NAME:-$DEFAULT_SKILL_NAME}}"

if [ "$SKILL_NAME" != "$DEFAULT_SKILL_NAME" ]; then
  echo "Error: this repo pins the skill name to '$DEFAULT_SKILL_NAME' (generate-css-wisdom.js and .gitignore reference it)." >&2
  exit 1
fi

REPO_ROOT="$(git -C "$ROOT_DIR" worktree list | head -1 | awk '{print $1}')"
DOCS_DIR="$ROOT_DIR/src/content/docs"

if [ ! -d "$DOCS_DIR" ]; then
  echo "Error: Documentation directory not found at $DOCS_DIR"
  exit 1
fi

ensure_symlink() {
  local link_path="$1"
  local target="$2"
  if [ -L "$link_path" ] || [ -e "$link_path" ]; then
    rm -rf "$link_path"
  fi
  ln -s "$target" "$link_path"
}

resolve_targets() {
  case "$TARGET_MODE" in
    claude) echo "claude" ;;
    codex) echo "codex" ;;
    both) echo "claude codex" ;;
    auto)
      local has_claude=""
      local has_codex=""
      [ -d "$HOME/.claude" ] && has_claude="true"
      [ -d "$HOME/.codex" ] && has_codex="true"

      if [ "$has_claude" = "true" ] && [ "$has_codex" = "true" ]; then
        echo "claude codex"
      elif [ "$has_codex" = "true" ]; then
        echo "codex"
      else
        echo "claude"
      fi
      ;;
  esac
}

wire_skill() {
  local target="$1"
  local skill_dir="$ROOT_DIR/.$target/skills/$SKILL_NAME"
  local global_skills_dir="$HOME/.$target/skills"
  local claude_skill_dir="$ROOT_DIR/.claude/skills/$SKILL_NAME"

  mkdir -p "$skill_dir"

  ensure_symlink "$skill_dir/docs" "$REPO_ROOT/src/content/docs"
  echo "  [$target] Created docs symlink -> $REPO_ROOT/src/content/docs"

  if [ -d "$ROOT_DIR/src/content/docs-ja" ]; then
    ensure_symlink "$skill_dir/docs-ja" "$REPO_ROOT/src/content/docs-ja"
    echo "  [$target] Created docs-ja symlink -> $REPO_ROOT/src/content/docs-ja"
  fi

  if [ ! -f "$claude_skill_dir/SKILL.md" ]; then
    echo "Error: $claude_skill_dir/SKILL.md not found." >&2
    echo "generate-css-wisdom.js should run before setup-doc-skill.sh." >&2
    exit 1
  fi

  if [ "$target" = "codex" ]; then
    cp "$claude_skill_dir/SKILL.md" "$skill_dir/SKILL.md"
    echo "  [codex] Copied generated SKILL.md from .claude"
  else
    echo "  [claude] SKILL.md present (generated by generate-css-wisdom.js)"
  fi

  mkdir -p "$global_skills_dir"
  ensure_symlink "$global_skills_dir/$SKILL_NAME" "$skill_dir"

  echo "  [$target] Project skill: $skill_dir"
  echo "  [$target] Global symlink: $global_skills_dir/$SKILL_NAME"
}

echo ""
echo "=== css-wisdom Skill Setup ==="
echo ""

read -r -a TARGETS <<< "$(resolve_targets)"
echo "Target: $TARGET_MODE -> ${TARGETS[*]}"
echo ""

for target in "${TARGETS[@]}"; do
  wire_skill "$target"
done

echo ""
echo "Done! Skill '$SKILL_NAME' is ready."
echo ""
echo "Use --target claude, --target codex, or --target both to override auto-detection."
echo "In Claude Code, use: /$SKILL_NAME <topic>"
echo "In Codex, use: \$$SKILL_NAME <topic>"
echo ""
